import '../../public/assets/css/normalize.css';
import '../../public/assets/css/variables.css';
import { Inter } from 'next/font/google';
import Navigation from '../components/Navigation';
import Footer from '../components/Footer';
import Provider from '@/redux/providers';
import styles from './layout.module.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portafolio Julian Gomez M',
  description: 'Generated by create next app',
  keywords: ['Julian Gomez', 'portfolio']
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={styles.layout__container} lang="en">
      <body className={styles.layout__body}>
        <Provider>
          <nav className={styles.layout__navigation}>
            <Navigation />
          </nav>
          {children}
          <footer className={styles.layout__footer}>
            <Footer />
          </footer>
        </Provider>
      </body>
    </html>
  )
}
