import '../../public/assets/css/normalize.css';
import '../../public/assets/css/variables.css';
import { Inter } from 'next/font/google';
import Navigation from '../components/Navigation';
import Footer from '../components/Footer';
import Provider from '@/redux/providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portafolio Julian Gomez M',
  description: 'Generated by create next app',
  keywords: ['Julian Gomez', 'portfolio']
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Navigation />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
